name: Python Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.8'
      - run: git clone 
      - run: pip install -r requirements.txt
      - run: python -m pytest tests/test_email_send.py