name: Python Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.8'
      - run: apt install -y git
      - run: git config --global user.name "Suryapag"
      - run: git config --global user.email "suryapa9092@gmail.com"
      - run: git clone git@github.com:Suryapag/cloud-cost-optimizer_-_monitor.git
        working-directory: cloud-cost-optimizer_-_monitor
        env:
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      - run: pip install -r requirements.txt
      - run: python -m pytest tests/test_email_send.py