name: Python Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Configure Git
        run: |
          git config --global user.name "Suryapag"
          git config --global user.email "suryapa9092@gmail.com"

      - name: Clone Test Repository
        run: git clone https://github.com/Suryapag/cloud-cost-optimizer_-_monitor.git

      - name: Install Requirements
        run: pip install -r cloud-cost-optimizer_-_monitor/requirements.txt

      - name: Run Pytest
        run: python tests/test_email_send.py
        working-directory: cloud-cost-optimizer_-_monitor
        
      - name: Debug ENV values
        run: |
          echo "EMAIL_HOST=$EMAIL_HOST"
          echo "EMAIL_HOST=$EMAIL_HOST"
          echo "EMAIL_PORT=$EMAIL_PORT"
          echo "EMAIL_HOST_USER=$EMAIL_HOST_USER"
        env:
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}